## Each new term in the Fibonacci sequence is generated by adding the previous
## two terms. By starting with 1 and 2, the first 10 terms will be:

## 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

## By considering the terms in the Fibonacci sequence whose values do not exceed
## four million, find the sum of the even-valued terms.

# closed form function for value of nth Fibonacci number
# https://en.wikipedia.org/wiki/Fibonacci_number#Closed-form_expression
fibn <- function(n) {
    phi <- (1 + sqrt(5)) / 2
    round(phi ** n / sqrt(5))
}

# what is the highest n for with fibn(n) < 4000000?
# 4e6 > phi ** n / sqrt(5)
# 4e6 * sqrt(5) > phi ** n
# 4e6 * sqrt(5) > (1 + sqrt(5) / 2) ** n
# log(4e6 * sqrt(5)) > n * log((1 + sqrt(5) / 2))
# log(4e6 * sqrt(5)) / log((1 + sqrt(5)) / 2) > n
# 33.26295 > n

library(purrr)
problem2 <- function() {
    fibn(1:33) %>%
        keep(~ . %% 2 == 0) %>%
        sum()
}

problem2()
