## The sequence of triangle numbers is generated by adding the natural numbers.
## So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first
## ten terms would be:

##    1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

## Let us list the factors of the first seven triangle numbers:

## 1: 1
## 3: 1,3
## 6: 1,2,3,6
## 10: 1,2,5,10
## 15: 1,3,5,15
## 21: 1,3,7,21
## 28: 1,2,4,7,14,28
## We can see that 28 is the first triangle number to have over five divisors.

## What is the value of the first triangle number to have over five hundred
## divisors?

prime_factors <- function(x) {
    # the product of the first 15 primes is 614,889,782,588,491,392, bigger than
    # i expect to deal with, so we will set that as our limit
    if (x > 6.148898e+17) {
        stop("Input `x` is too big for this function to handle.")
    }

    primes <- numeric(15)
    powers <- numeric(15)
    nth <- 1L

    i <- 2
    while(i <= floor(sqrt(x))) {
        if (x %% i == 0) {
            primes[nth] <- i
            powers[nth] <- 1
            x <- x / i

            while (x %% i == 0) {
                powers[nth] <- powers[nth] + 1
                x <- x / i
            }

            nth <- nth + 1
        }

        i <- ifelse(i == 2, 3, i + 2)
    }

    if (x > 1) {
        primes[nth] <- x
        powers[nth] <- 1
    }

    list(primes = keep(primes, ~ . > 0),
         powers = keep(powers, ~ . > 0))
}

# https://mathschallenge.net/index.php?section=faq&ref=number/number_of_divisors
num_divisors <- function(x) {
    pf <- prime_factors(x)
    prod(pf$powers + 1)
}

n <- 28
i <- 8
while (num_divisors(n) < 500) {
    n <- n + i
    i <- i + 1
}
